# This is an example neoforge.mods.toml file. It contains the data Neoforge uses to load your mod.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, with square brackets are sections.
# Lines that begin with # are comments and will not be parsed.

# The name of the mod loader type to load - for regular Neoforge mods it should be neoforge
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular Neoforge it will be the neoforge version
loaderVersion="[4,)" #mandatory

# The license for your mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT" #mandatory

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="createjeicompat" #mandatory

# The version number of the mod
version="${mod_version}" #mandatory

# A display name for the mod
displayName="Create JEI Compat" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="https://change.me.to.your.update.json.example.invalid/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.homepage.example.invalid/" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional

# A text field displayed in the mod UI
description='''
JEI compatibility mod for Create mod with enhanced sequenced assembly display
''' #mandatory

# A dependency - use the . to indicate dependency for a specific modid. This depends on neoforge being loaded.
# neoforge coremod specific settings - DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING
[[dependencies.createjeicompat]] #optional
    modId="neoforge" #mandatory
    type="required" #mandatory
    versionRange="[21.1.73,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.createjeicompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.createjeicompat]]
    modId="create"
    type="required"
    versionRange="[6.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createjeicompat]]
    modId="jei"
    type="required"
    versionRange="[18.0.0,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config="createjeicompat.mixins.json"

